name: admin_template_core
description: A platform-agnostic library that extends Dart language feature.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.2
  recase: ^3.0.0
  quiver: ^2.1.3
  built_value: ^7.1.0
  logging: ^0.11.4

dev_dependencies:
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
