name: ad_stream_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ad_stream:
    path: ../ad_stream

  # An utility provides a Dependency Injection library.
  # see more at google/inject.dart
  inject:
    path: ../vendor/inject

  # The plugin has reached a stable API.
  # They guarantee that version 1.0.0 will be backward compatible with 0.5.y+z.
  # Use below dependency constraint to allow a smoother ecosystem migration.
  shared_preferences: ">=0.5.7+3 <2.0.0"

  # Request permission to access camera and microphone
  permission_handler: 5.0.1+1

  animations: 1.1.1
  provider: 4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  inject_generator:
    path: ../vendor/inject_generator

flutter:
  uses-material-design: true
