name: ad_stream_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ad_stream:
    path: ../ad_stream

  # The plugin has reached a stable API.
  # They guarantee that version 1.0.0 will be backward compatible with 0.5.y+z.
  # Use below dependency constraint to allow a smoother ecosystem migration.
  shared_preferences: ">=0.5.7+3 <2.0.0"

  # Request permission to access camera and microphone
  permission_handler: 5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
