name: twilio_video
description: A new flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  meta: 1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.twilio_video
        pluginClass: TwilioVideoPlugin
      ios:
        pluginClass: TwilioVideoPlugin
