name: admin_template_annotation
description: A new Flutter package.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2