name: sample
version: 0.0.1-dev

description: Explore dart extension libraries to work with immutable values.

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  built_value: ^7.0.9
  built_collection: ^4.3.2
  collection: ^1.14.12

dev_dependencies:
  pedantic: ^1.4.0
  test: ^1.0.0
