// Autogenerated from Pigeon (v0.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTHelloMessage;
@class FLTReplyMessage;

@interface FLTHelloMessage : NSObject
@property(nonatomic, copy, nullable) NSString * name;
@end

@interface FLTReplyMessage : NSObject
@property(nonatomic, copy, nullable) NSString * reply;
@end

@protocol FLTHelloApi
-(void)initialize:(FlutterError *_Nullable *_Nonnull)error;
-(void)hello:(FLTHelloMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable FLTReplyMessage *)helloAndReply:(FLTHelloMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTHelloApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTHelloApi> _Nullable api);

NS_ASSUME_NONNULL_END
